// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import React, { Suspense } from "react";
import "./globals.css";
// import { Figtree } from "next/font/google";
// import PropTypes from "prop-types";
// import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
// import Script from "next/script";
// import { Toaster } from "react-hot-toast";
// import { NextUIProvider } from "@nextui-org/react";
// import Loading from "./loading";

// export const metadata = {
//   title: "Uslot | Know your self , then educate",
//   description:
//     "Our programme offers personalized one-on-one and group mentoring with dedicated teachers and mentors for every student. Covering academics, non-academics, and 'Your Choice' courses, we provide flexible learning for KG to 12th grade. Discover a world of learning tailored to your passions and needs",
// };

// const figTree = Figtree({
//   subsets: ["latin"],
//   display: "swap",
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <Script src="http://code.jquery.com/jquery-latest.min.js"></Script>
        <Script src="jquery.drawsvg.js"></Script>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-0D5B53DLFG"
        ></Script>
        <Script>
          {`window.dataLayer = window.dataLayer || [];
             function gtag(){dataLayer.push(arguments);} 
            gtag('js', new Date());   gtag('config', 'G-0D5B53DLFG');`}
        </Script> */}
      </head>
      {/* <body className={figTree.className}> */}
      <body >
          <Header />
          {/* <Suspense fallback={<Loading />}>{children}</Suspense> */}
          <Suspense >{children}</Suspense>
          <Footer />
      </body>
    </html>
  );
}

// RootLayout.propTypes = {
//   children: PropTypes.node.isRequired,
// };